export const MONTHS_DATA = [
  {
    name: "janvier",
    title: "janvier",
    image: "janvier.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 0,
    gradient: ["#F9F9F9", "#84B9BF", "#A6DACD", "#CDEFDB", "#FBFEFB"],
    season: "winter",
  },
  {
    name: "février",
    title: "février",
    image: "fevrier.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 2,
    gradient: [
      "#F9F9F9",
      "#84B9BF",
      "#9BD4B6",
      "#BCE5B5",
      "#EBF2D3",
      "#FDFAF4",
    ],
    season: "winter",
  },
  {
    name: "mars",
    title: "mars",
    image: "mars.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 3521,
    gradient: [
      "#4AA0AB",
      "#57B5AD",
      "#65BEA3",
      "#74C69C",
      "#89D797",
      "#AAE6A1",
      "#D4F1BB",
      "#F2F9D9",
      "#FEFEFA",
    ],
    season: "spring",
  },
  {
    name: "avril",
    title: "avril",
    image: "avril.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 20853,
    gradient: [
      "#2E626C",
      "#347376",
      "#3A807B",
      "#41897D",
      "#48937E",
      "#4E9C7E",
      "#55A57E",
      "#5DAD7D",
      "#64B67C",
      "#6CBE7B",
      "#74C67A",
      "#7BCC7B",
      "#87D282",
      "#93D789",
      "#A0DC90",
      "#ACE198",
      "#B8E6A1",
      "#C4EAA9",
      "#CEEDB2",
      "#D9F1BB",
      "#E2F4C5",
      "#EAF7CF",
      "#F1F9D9",
      "#F7FBE4",
      "#FBFDEF",
      "#FEFEFA",
    ],
    season: "spring",
  },
  {
    name: "mai",
    title: "mai",
    image: "mai.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 4426,
    gradient: [
      "#58A18F",
      "#66AE93",
      "#74BB97",
      "#83C79B",
      "#94D1A1",
      "#A5DBA9",
      "#B8E5B6",
      "#CFEDC9",
      "#E4F4DC",
      "#F5FBF1",
    ],
    season: "spring",
  },
  {
    name: "juin",
    title: "juin",
    image: "juin.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 1041,
    gradient: [
      "#98C585",
      "#A6CE8E",
      "#B3D697",
      "#C1DDA1",
      "#CEE4AC",
      "#DAEAB7",
      "#E5F0C3",
      "#EFF4D0",
      "#F6F8DD",
      "#FCFCEB",
    ],
    season: "summer",
  },
  {
    name: "juillet",
    title: "juillet",
    image: "juillet.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 383,
    gradient: [
      "#83B352",
      "#A3C867",
      "#C1DA80",
      "#DCE89C",
      "#F0F3BB",
      "#FBF9DE",
    ],
    season: "summer",
  },
  {
    name: "août",
    title: "août",
    image: "aout.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 378,
    gradient: [
      "#AFBC67",
      "#C9CF7A",
      "#DEDD90",
      "#EBE4A9",
      "#F5ECC5",
      "#FCF5E4",
    ],
    season: "summer",
  },
  {
    name: "septembre",
    title: "septembre",
    image: "septembre.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 1352,
    gradient: [
      "#E7BF65",
      "#F4C574",
      "#FDCB86",
      "#FFD29B",
      "#FFDBB4",
      "#FFE6D0",
      "#FFF6F0",
    ],
    season: "autumn",
  },
  {
    name: "octobre",
    title: "octobre",
    image: "octobre.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 4832,
    gradient: [
      "#F2908B",
      "#F99F92",
      "#FEAE9A",
      "#FFBDA3",
      "#FFCCAE",
      "#FFDAB9",
      "#FFE7C6",
      "#FFF1D4",
      "#FFF9E3",
      "#FFFEF3",
    ],
    season: "autumn",
  },
  {
    name: "novembre",
    title: "novembre",
    image: "novembre.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 15943,
    gradient: [
      "#DA759F",
      "#DC7C9C",
      "#DD839A",
      "#DF8999",
      "#E09099",
      "#E29799",
      "#E4A09D",
      "#E5ACA4",
      "#E7B7AB",
      "#E9C0B1",
      "#EACAB8",
      "#ECD2BE",
      "#EEDAC5",
      "#F0E1CB",
      "#F2E7D2",
      "#F3ECD8",
      "#F5F1DF",
      "#F7F5E5",
      "#F9F9EC",
      "#FBFBF2",
      "#FCFDF8",
    ],
    season: "autumn",
  },
  {
    name: "décembre",
    title: "décembre",
    image: "decembre.png",
    description: "Macron annonce le confinement blabla c’est incvroyable comment on va faire<br>Macron annonce le confinement blabla c’est incvroyable comment on va faire",
    deaths: 11901,
    gradient: [
      "#F9F9F9",
      "#9BA8E1",
      "#A1B5E3",
      "#A7C2E5",
      "#ADCDE7",
      "#B2D8E9",
      "#B8E1EB",
      "#BEEAED",
      "#C4EFED",
      "#CAF1EA",
      "#D1F3E8",
      "#D7F4E8",
      "#DDF6E8",
      "#E3F8EA",
      "#E9F9ED",
      "#EFFBF0",
      "#F6FDF6",
    ],
    season: "winter",
  },
]
