export const MODELS = [
    {
        filename: "arbre-fancy-automne",
        type: "tree",
        season: "autumn",
        loaded: false,
    },
    {
        filename: "arbre-fancy-ete",
        type: "tree",
        season: "summer",
        loaded: false,
    },
    {
        filename: "arbre-fancy-printemps",
        type: "tree",
        season: "spring",
        loaded: false,
    },
    {
        filename: "arbre-mort",
        type: "tree",
        season: "winter",
        loaded: false,
    },
    {
        filename: "arbre-rond-automne",
        type: "tree",
        season: "autumn",
        loaded: false,
    },
    {
        filename: "arbre-rond-ete",
        type: "tree",
        season: "summer",
        loaded: false,
    },
    {
        filename: "arbre-rond-printemps",
        type: "tree",
        season: "spring",
        loaded: false,
    },
    {
        filename: "birds",
        type: "birds",
        season: "all",
        loaded: false,
    },
    {
        filename: "buisson-automne",
        type: "vegetation",
        season: "autumn",
        loaded: false,
    },
    {
        filename: "buisson-ete",
        type: "vegetation",
        season: "summer",
        loaded: false,
    },
    {
        filename: "buisson-neige",
        type: "vegetation",
        season: "winter",
        loaded: false,
    },
    {
        filename: "buisson-printemps",
        type: "vegetation",
        season: "spring",
        loaded: false,
    },
    {
        filename: "champignon",
        type: "vegetation",
        season: "autumn",
        loaded: false,
    },
    {
        filename: "cloud-small",
        type: "cloud",
        season: "all",
        loaded: false,
    },
    {
        filename: "cloud",
        type: "cloud",
        season: "all",
        loaded: false,
    },
    {
        filename: "fleur-blanche",
        type: "vegetation",
        season: "spring",
        loaded: false,
    },
    {
        filename: "fleur-rouge",
        type: "vegetation",
        season: "spring",
        loaded: false,
    },
    {
        filename: "herbe-automne",
        type: "vegetation",
        season: "autumn",
        loaded: false,
    },
    {
        filename: "herbe-ete",
        type: "vegetation",
        season: "summer",
        loaded: false,
    },
    {
        filename: "herbe-hiver",
        type: "vegetation",
        season: "winter",
        loaded: false,
    },
    {
        filename: "herbe-printemps",
        type: "vegetation",
        season: "spring",
        loaded: false,
    },
    {
        filename: "sapin-automne",
        type: "tree",
        season: "autumn",
        loaded: false,
    },
    {
        filename: "sapin-ete",
        type: "tree",
        season: "summer",
        loaded: false,
    },
    {
        filename: "sapin-neige",
        type: "tree",
        season: "winter",
        loaded: false,
    },
    {
        filename: "sapin-printemps",
        type: "tree",
        season: "spring",
        loaded: false,
    },
]